name: release project

on:
  workflow_call:
    inputs:
      changelogPath:
        required: true
        type: string
        description: The path to CHANGELOG.md

jobs:
  extractChangelog:
    uses: ./.github/workflows/extract_changelog.yaml
    with:
      changelogPath: ${{inputs.changelogPath}}
  checkVersion:
    needs: extractChangelog
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.tag-exists.outputs.exists }}
    steps:
      - name: check if tag exists
        uses: mukunku/tag-exists-action@5dfe2bf779fe5259360bb10b2041676713dcc8a3 # v1.1.0
        id: tag-exists
        with:
          tag: ${{ needs.extractChangelog.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  createBranch:
    needs: [extractChangelog, checkVersion]
    if: needs.checkVersion.outputs.exists == 'false'
    uses: ./.github/workflows/create_js_branch.yaml
    with:
        version: ${{ needs.extractChangelog.outputs.version }}
  createRelease:
    needs: [checkVersion, extractChangelog]
    permissions:
      contents: write
    if: needs.checkVersion.outputs.exists == 'false'
    uses: ./.github/workflows/create_release.yaml
    with:
      branch: release/${{ needs.extractChangelog.outputs.version }}
      version: ${{ needs.extractChangelog.outputs.version }}
      body: ${{ needs.extractChangelog.outputs.body }}